### PR TITLE
Fixed bugs in saving centers

### PR DESCRIPTION
**Pull request by feranick**
Two patches to fix a crash when saving the centers before an acquisition, and to avoid redundancy in saving centers after acquisition.

### CODE REVIEW

**Comment by andim** [comment]
Could you simply remove the saveCenter method of the worker? There is not much point in keeping the duplicated code. Even when the worker is instantiated your new code still saves the center without needing to call the worker.

**Comment by feranick** [comment]
I thought of that, in fact that was exactly my initial solution. However, the two functions servers two different purposes in fact implement two different strategies. The first SaveCenter outside of the worker is a failsafe to save only and uniquely the center defined for one image before any acquisition, so without any recognition of all the others. This is is useful for calibration or to set the starting point consistently. The one in the worker actually saves the position of the center for *all* the images. Under normal circumstances the center position does not move, but we have been recently keep adjusting it to compensate for motion, so this function tracks that. Hence, we have two different methods.

**Comment by andim** [comment]
Ok, I did not recall this subtle difference. I will merge your fix then.

**Comment by feranick** [comment]
Thanks. There was actually no difference at least in the way it was originally intended. It is now factual as a matter of use and necessity. Thanks!

**Pull request merged**
