### PR TITLE
Use pandas dataframe for saving intensities and spot locations

### PR DESCRIPTION
**Pull request by feranick**
Currently intensities are internally saved as numpy arrays, making it difficult to add other variables (such as center coordinates, spot location and size). This patch changes this by using pandas dataframes. The resulting code is cleaner, more transparent and allows for traking all of the above. In the future it will be used to save independently also spot locations and center coordinates replacing the current binary pkl files.

Candidate fix for #27

### CODE REVIEW

**Comment by feranick** [comment]
SIde note: the average is now always saved: there is little point to not saving it regardless of the checkbox. Good for consistency.

**Comment by andim** [comment]
Ok I will try and look through it. Having an extra dependency on pandas is not necessarily ideal, but I guess now that the whole install is pip based anyway it does not matter much to the end user. One could possibly achieve much of the same with `numpy.savez` (https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.savez.html) which also allows to store several arrays.

**Comment by feranick** [comment]
Pandas are now as standard as numpy is. Numpy is great, but not much for dealing with a diversity of datatypes and sizes. The rigidity of numpy in dealing with this diversity makes the resulting code cumbersome often resulting in the need of stuff like pikles and the likes. Once a pandas dataframe is in place, it's trivial to recall things at once, for example selecting a spot may show you the related curve on the plot in bold. Not that this cannot be achieved with other methods, just that with dataframes, this is completely within a line of code. 

My vote is for the extra dependency. If adopted I am going it to use it for a lot of other uses within easyleed.

**Comment by andim** [comment]
I like pandas as well and use it quite a bit in my other work. It's true that it has quickly become a core python library but it is still a rather large dependency. I agree that going forward we could potentially refactor quite a bit of the code in more elegant and concise ways using pandas, so I'm ok with including it.

**Comment by feranick** [comment]
Thanks. Once it's merged, I'll push a PR where once you select a peak, it highlights the corresponding curve. This is a feature that was somehow requested and one that should improve versatility in other places.

Thanks again,
Nicola



On 11/8/17 10:46 PM, Andreas Mayer wrote:

I like pandas as well and use it quite a bit in my other work. It's true that it has quickly become a core python library but it is still a rather large dependency. I agree that going forward we could potentially refactor quite a bit of the code in more elegant and concise ways using pandas, so I'm ok with including it.

**Comment by feranick** [comment]
I share your point about pandas's size. That said, and for perspective, when you look at QT dependency (just runtime for Windows for QT 5.9.2 it's 8GB) pandas look like an innocuous plugin...

On 11/8/17 10:46 PM, Andreas Mayer wrote:

I like pandas as well and use it quite a bit in my other work. It's true that it has quickly become a core python library but it is still a rather large dependency. I agree that going forward we could potentially refactor quite a bit of the code in more elegant and concise ways using pandas, so I'm ok with including it.

**Comment by andim** [comment]
I took a more detailed view at the code. Am I seeing things correctly that following the tidy data paradigm (https://en.wikipedia.org/wiki/Tidy_data), the csv has a row for every energy with the columns having all the different information (spot intensities, spot positions, background subtraction flag, center position)?

I am wondering whether constructing a DataFrame for every column and then concatenating them step by step is the most elegant way of constructing the overall dataframe. Wouldn't it be nicer to simply add all the columns to a dictionary and then construct the DataFrame all at once?

**Comment by feranick** [comment]
On 11/8/17 11:00 PM, Andreas Mayer wrote:
>
> I took a more detailed view at the code. Am I seeing things correctly 
> that following the tidy data paradigm 
> (https://en.wikipedia.org/wiki/Tidy_data), the csv has a row for every 
> energy with the columns having all the different information (spot 
> intensities, spot positions, background subtraction flag, center 
> position)?
>
Yes, that is correct.

> I am wondering whether constructing a DataFrame for every column and 
> then concatenating them step by step is the most elegant way of 
> constructing the overall dataframe. Wouldn't it be nicer to simply add 
> all the columns to a dictionary and then construct the DataFrame all 
> at once?
>

Yes, let me look through it tomorrow.

**Comment by feranick** [comment]
OK, a couple of changes. First, I moved the creation of the dataframe into a separate method, which is then called at the end of an extraction. The dataframe is then available for any task needed (saving intensities, for example, is now immediately available)

I then simplified the generation of the dataframe as discussed. I am not a big fan of highly convoluted lists, so I create columns as needed within the same dataframe.

**Comment by andim** [comment]
Thanks for the changes. Code looks good to me know. Is it good from your side for merging?

**Comment by feranick** [comment]
Yes, please.

On 11/9/17 10:39 AM, Andreas Mayer wrote:

Thanks for the changes. Code looks good to me know. Is it good from your side for merging?

**Pull request merged**
